version: '3.8'

services:
  application:
    container_name: poc-clean-go
    image: poc-clean-go:latest
    restart: always
    build: .
    environment:
      APP_ENV: dev-container
      MONGODB_URI: mongodb://mongodb:27017
      FILIAL_DATABASE: Cadastro
      FILIAL_COLLECTION: Filial
      BROKER_ADDRESS: kafka:9092
      TOPIC: filial-topic
      GROUP_ID: filial-group
    ports:
      - "8086:8086"